
# Board settings.
#BOARD = atmega328
#BOARD = pro5v328

#MON_SPEED = 9600

# Where to find header files and libraries.
#INC_DIRS = ./inc
LIB_DIRS = ../../EPD/libraries/EReader /local/arduino-100/libraries/Wire/ /local/arduino-100/libraries/Wire/utility/ /local/arduino-100/libraries/SPI/ /local/arduino-100/libraries/SD /local/arduino-100/libraries/SD/utility/

include ../../../libs/Makefile.master

